networks:
  default:
  traefik:
    external: true

services:
  uptimekuma:
    image: louislam/uptime-kuma:1-alpine
    restart: unless-stopped
    # ports:
    #   - 3001:3001
    volumes:
    # use volumes folder for data persistance
    - ./volumes/data:/app/data

  uptimekuma-authentik-proxy:
    image: ghcr.io/goauthentik/proxy
    # ports:
    #     - 9000:9000
    #     - 9443:9443
    environment:
        AUTHENTIK_HOST: https://${AUTHENTIK_DOMAIN}
        AUTHENTIK_INSECURE: "false"
        AUTHENTIK_TOKEN: ${AUTHENTIK_TOKEN}

    networks:
    - traefik # add to traefik network
    - default # add to default (stack internal) network

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptimekuma.rule=Host(`${UPTIMEKUMA_DOMAIN}`)"
      - "traefik.http.routers.uptimekuma.entrypoints=websecure"
