networks:
  default:
  traefik:
    external: true

services:
  uptimekuma:
    image: louislam/uptime-kuma:1-alpine
    restart: unless-stopped
    # ports:
    #   - 3001:3001
    volumes:
    # use volumes folder for data persistance
    - ./volumes/data:/app/data

    networks:
    - traefik # add to traefik network
    # - default # add to default (stack internal) network

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptimekuma.rule=Host(`${UPTIMEKUMA_DOMAIN}`)"
      - "traefik.http.routers.uptimekuma.entrypoints=websecure"
      - "traefik.http.routers.uptimekuma.middlewares=authentik@file"
